#!/usr/bin/env python3
"""Build the SecOC SWS-clause-to-evidence traceability matrix.

Scans three sources:

  1. ``Autosar_SecOC/source/SecOC/`` — every clause REFERENCED in the
     real implementation. The clause is "implemented" if it is mentioned
     here.
  2. ``Autosar_SecOC/test/*.cpp`` — every clause asserted by a unit test
     (looked up via the SWS_SecOC_NNNNN comment marker that the test file
     adds next to the relevant assertion).
  3. ``integrated_simulation_env/scenarios/sc_*.c`` — every clause
     covered by an ISE scenario (same comment marker convention).

Emits a CSV at ``--out`` (default summary/sws_traceability.csv) and a
short Markdown summary at the same path with ``.md`` extension.

Usage:
  python3 build_sws_traceability.py --repo-root /path/to/repo \
                                    --out /path/to/results/<t>/summary
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path
from typing import Dict, List, Set

CLAUSE_RE = re.compile(r"SWS_SecOC_(\d{5})")


def collect(paths: List[Path]) -> Dict[str, Set[str]]:
    """Return {clause_id: {file:line, ...}}."""
    out: Dict[str, Set[str]] = {}
    for path in paths:
        if not path.exists():
            continue
        for f in path.rglob("*"):
            if not f.is_file():
                continue
            if f.suffix not in (".c", ".cpp", ".h", ".hpp"):
                continue
            try:
                lines = f.read_text(errors="ignore").splitlines()
            except Exception:
                continue
            for n, line in enumerate(lines, start=1):
                for m in CLAUSE_RE.finditer(line):
                    cid = "SWS_SecOC_" + m.group(1)
                    out.setdefault(cid, set()).add(f"{f}:{n}")
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--repo-root", required=True, help="repo root containing Autosar_SecOC/ and integrated_simulation_env/")
    p.add_argument("--out", required=True, help="output dir (writes sws_traceability.csv + .md)")
    args = p.parse_args()

    root = Path(args.repo_root).resolve()
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    impl    = collect([root / "Autosar_SecOC" / "source" / "SecOC",
                       root / "Autosar_SecOC" / "include" / "SecOC"])
    unit    = collect([root / "Autosar_SecOC" / "test"])
    ise     = collect([root / "integrated_simulation_env" / "scenarios"])

    all_clauses = sorted(set(impl) | set(unit) | set(ise))

    csv_path = out_dir / "sws_traceability.csv"
    with csv_path.open("w", newline="") as fp:
        w = csv.writer(fp)
        w.writerow(["clause", "implementation_refs", "unit_test_refs", "ise_scenario_refs", "status"])
        for c in all_clauses:
            i = sorted(impl.get(c, set()))
            u = sorted(unit.get(c, set()))
            e = sorted(ise.get(c, set()))
            if not i and (u or e):
                status = "EVIDENCE_ONLY"
            elif i and (u or e):
                status = "IMPL+EVIDENCE"
            elif i:
                status = "IMPL_ONLY"
            else:
                status = "?"
            w.writerow([c, " | ".join(i), " | ".join(u), " | ".join(e), status])

    # Counts.
    n_total       = len(all_clauses)
    n_impl_evid   = sum(1 for c in all_clauses if (impl.get(c) and (unit.get(c) or ise.get(c))))
    n_impl_only   = sum(1 for c in all_clauses if (impl.get(c) and not (unit.get(c) or ise.get(c))))
    n_evid_only   = sum(1 for c in all_clauses if (not impl.get(c) and (unit.get(c) or ise.get(c))))
    n_unit        = sum(1 for c in all_clauses if unit.get(c))
    n_ise         = sum(1 for c in all_clauses if ise.get(c))
    n_both        = sum(1 for c in all_clauses if unit.get(c) and ise.get(c))

    md_path = out_dir / "sws_traceability.md"
    with md_path.open("w") as fp:
        fp.write("# SWS_SecOC Clause Traceability Matrix\n\n")
        fp.write("Auto-generated by `reports/build_sws_traceability.py`. ")
        fp.write("Scans `Autosar_SecOC/source/SecOC/`, `Autosar_SecOC/test/*.cpp`, ")
        fp.write("and `integrated_simulation_env/scenarios/sc_*.c` for the literal token ")
        fp.write("`SWS_SecOC_NNNNN`.\n\n")
        fp.write("## Summary\n\n")
        fp.write(f"| Metric | Count |\n|---|---|\n")
        fp.write(f"| Distinct clauses found anywhere | {n_total} |\n")
        fp.write(f"| Implemented AND with test evidence (unit and/or ISE) | {n_impl_evid} |\n")
        fp.write(f"| Implemented but no test evidence yet | {n_impl_only} |\n")
        fp.write(f"| Evidence cited but no implementation token (likely doc-only) | {n_evid_only} |\n")
        fp.write(f"| Cited by unit tests | {n_unit} |\n")
        fp.write(f"| Cited by ISE scenarios | {n_ise} |\n")
        fp.write(f"| Cited by both layers | {n_both} |\n\n")
        coverage = (100.0 * (n_impl_evid + n_evid_only) / max(1, n_total))
        fp.write(f"**Evidence coverage: {coverage:.1f}% of distinct clauses have at least one test trace.**\n\n")
        fp.write("## Per-clause table\n\n")
        fp.write("Refs are `path:line`. Multiple refs separated by ` | `.\n\n")
        fp.write("| Clause | Status | Impl refs | Unit-test refs | ISE-scenario refs |\n")
        fp.write("|---|---|---|---|---|\n")
        for c in all_clauses:
            i = sorted(impl.get(c, set()))
            u = sorted(unit.get(c, set()))
            e = sorted(ise.get(c, set()))
            if i and (u or e):
                status = "IMPL+EVIDENCE"
            elif i:
                status = "IMPL only"
            else:
                status = "evidence only"
            i_str = "<br>".join(str(Path(r).relative_to(root)) for r in i) or "—"
            u_str = "<br>".join(str(Path(r).relative_to(root)) for r in u) or "—"
            e_str = "<br>".join(str(Path(r).relative_to(root)) for r in e) or "—"
            fp.write(f"| {c} | {status} | {i_str} | {u_str} | {e_str} |\n")

    print(f"[trace] {n_total} clauses; impl+evidence={n_impl_evid}, impl-only={n_impl_only}, evidence-only={n_evid_only}")
    print(f"[trace] wrote {csv_path}")
    print(f"[trace] wrote {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
